### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by OSINT-d** [Josue87/AnalyticsRelationships#1]
Hi,
when running the script this error message appears:

File "analyticsrelationships.py", line 12
SyntaxError: Non-ASCII character '\xe2' in file analyticsrelationships.py on line 13, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

How to fix it?

thx

**Comment by Josue87** [comment]
Hello,

I think you are using Python2. If you are not sure which version you have, run ```python --version```.
To run the script you need Python3.6 or higher.

Best regards!
